### ISSUE TITLE
Uninstaller (current user) does not work

### ISSUE THREAD

**Issue by jzpt** [Bill-Stewart/SyncthingWindowsSetup#24] opened 2024-03-29 10:22 UTC
Running syncthing 1.27.4, I cannot uninstall: after starting it up, uninstaller keeps hanging on 0%

 
![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/119791530/c1968662-8296-49fc-9f9f-7c2fdf2ad8cc)

Task Manager shows nothings happening either
![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/119791530/9aa28cf7-be30-48d8-a3ee-0a5f55d0bb9a)

**Comment by Bill-Stewart** [comment] 2024-03-29 14:24
Sorry, I am not able to reproduce this. I would recommend starting the uninstaller with the `/LOG` parameter and check the content of the uninstaller log. Example:

    C:\Users\username\AppData\Local\Programs\Syncthing\uninstall\unins000.exe /LOG=C:\Users\username\Documents\uninstall.log

**Comment by jzpt** [comment] 2024-03-29 15:56
this is what came out of the log:

2024-03-29 16:45:26.982   Log opened. (Time zone: UTC+01:00)
2024-03-29 16:45:26.982   Setup version: Inno Setup version 6.2.2
2024-03-29 16:45:26.982   Original Uninstall EXE: C:\Users\~\AppData\Local\Programs\Syncthing\uninstall\unins000.exe
2024-03-29 16:45:26.982   Uninstall DAT: C:\Users\~\AppData\Local\Programs\Syncthing\uninstall\unins000.dat
2024-03-29 16:45:26.982   Uninstall command line: /SECONDPHASE="C:\Users\~\AppData\Local\Programs\Syncthing\uninstall\unins000.exe" /FIRSTPHASEWND=$F0C0E /LOG=E:\Syncthinguninstall.log
2024-03-29 16:45:26.983   Windows version: 10.0.19045  (NT platform: Yes)
2024-03-29 16:45:26.996   64-bit Windows: Yes
2024-03-29 16:45:26.996   Processor architecture: x64
2024-03-29 16:45:26.996   User privileges: None
2024-03-29 16:45:26.997   Administrative install mode: No
2024-03-29 16:45:26.997   Install mode root key: HKEY_CURRENT_USER
2024-03-29 16:45:26.997   Created temporary directory: C:\Users\~\AppData\Local\Temp\is-JVMLH.tmp
2024-03-29 16:45:27.011   -- DLL function import --
2024-03-29 16:45:27.011   Function name: GetUserNameExW
2024-03-29 16:45:27.011   DLL name: setup:secur32.dll
2024-03-29 16:45:27.011   Skipping.
2024-03-29 16:45:27.011   -- DLL function import --
2024-03-29 16:45:27.011   Function name: CompareVersionStrings
2024-03-29 16:45:27.011   DLL name: setup:files:UninsIS.dll
2024-03-29 16:45:27.011   Skipping.
2024-03-29 16:45:27.011   -- DLL function import --
2024-03-29 16:45:27.011   Function name: IsISPackageInstalled
2024-03-29 16:45:27.011   DLL name: setup:files:UninsIS.dll
2024-03-29 16:45:27.011   Skipping.
2024-03-29 16:45:27.011   -- DLL function import --
2024-03-29 16:45:27.011   Function name: UninstallISPackage
2024-03-29 16:45:27.011   DLL name: setup:files:UninsIS.dll
2024-03-29 16:45:27.011   Skipping.
2024-03-29 16:45:27.011   -- DLL function import --
2024-03-29 16:45:27.011   Function name: FindProcess
2024-03-29 16:45:27.011   DLL name: files:ProcessCheck.dll
2024-03-29 16:45:27.011   Skipping.
2024-03-29 16:45:27.011   Message box (Yes/No):
                          Are you sure you want to completely remove Syncthing and all of its components?
2024-03-29 16:45:29.241   User chose Yes.
2024-03-29 16:45:29.389   Exec: "C:\Users\~\AppData\Local\Programs\Syncthing\stctl.exe" --stop -q
2024-03-29 16:45:29.389   Exec exit code: 0

**Comment by Bill-Stewart** [comment] 2024-03-29 16:10
The next step after running `stctl.exe` is to remove the Syncthing firewall rule, which will provoke a UAC prompt if the uninstaller is not elevated. Please try removing the firewall rule manually before performing the uninstall with logging:

https://github.com/Bill-Stewart/SyncthingWindowsSetup/?tab=readme-ov-file#removing-the-firewall-rule-manually

**Comment by jzpt** [comment] 2024-03-29 23:01
I've entered the test command and it seems to hang

![cmd_oGDxTn49Wv](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/119791530/2f40d9a0-9fed-4c9e-9705-14299ef1d0d6)

**Comment by Bill-Stewart** [comment] 2024-03-30 05:15
Naturally, there's the problem. Perhaps you have an anti-malware program or something similar that's interfering with the WSH host. As I said, I can't reproduce it.

**Comment by jzpt** [comment] 2024-03-30 16:51
I exited the malware-program, temporarily disabled the firewall, and the uninstaller still hangs

**Comment by Bill-Stewart** [comment] 2024-03-30 16:54
Does this happen only on a single computer or on more than one computer?

**Comment by jzpt** [comment] 2024-03-30 16:56
I only use SyncThing on my Windows desktop and Steam Deck, and my installation is different on the latter.

**Comment by jzpt** [comment] 2024-03-30 17:10
Any way to bypass whatever it is cscript and wscript are supposed to do or to just uninstall the program manually. I am not good at this, I have tried everything I can personally thing of and it just doesn't work.

**Comment by Bill-Stewart** [comment] 2024-03-30 17:15
The uninstall consists of removing the Windows Firewall rule, the scheduled task (if you installed it), and the installation directory.

**Comment by jzpt** [comment] 2024-03-30 17:30
I've checked the Windows Firewall with Advanced Security console and I can't find a Syncthing rule there and I don't seem to have a scheduled task, so if I deleted the installation directory I should be good?

**Comment by Bill-Stewart** [comment] 2024-03-30 17:54
Yes

**Comment by Bill-Stewart** [comment] 2024-04-01 18:15
Closing as not reproducible

**Comment by Bill-Stewart** [comment] 2024-04-01 18:19
Closing as not reproducible

**Closed by Bill-Stewart** 2024-04-01 18:19 UTC
