### ISSUE TITLE
Syncthing does not start when installed by admin user without password 

### ISSUE THREAD

**Issue by koloved** [Bill-Stewart/SyncthingWindowsSetup#15] opened 2023-12-21 21:31 UTC
i look at services but the syncthing service was disabled and the was something wrong ( tried to edit service but password was not correct) 
then i add password to user and reinstall it , it working, but another issuse its not have privileges to write to my folder
i manually add Syncthing user to the folder (read wright privileges) and now its working

**Comment by Bill-Stewart** [comment] 2023-12-21 23:24
Your problem description is rather vague. Can you provide a specific set of steps that reproduce the problem? Specific error messages would also be helpful. (Without specific steps to reproduce and specific errors, it's hard to know what exactly is not working.)

**Comment by koloved** [comment] 2023-12-21 23:38
i mean , if your user with even admin rights do not have password , it will not work, i have that issue on two different PC , win 10 and 11

**Comment by Bill-Stewart** [comment] 2023-12-22 16:13
Sorry, but I don't understand what you are trying to say. There is no need to know the password for the `SyncthingServiceAcct` account because Setup sets it automatically, and you can easily reset the password using the `Reset-SyncthingServiceAccountPassword.ps1` script. I just tested Setup on a Windows 11 machine and it's working fine for me.

If you can provide a specific list of steps that reproduces the problem, please provide them. As noted previously, specific error message are best. (Otherwise, I'll need to close this because, so far, I am not able to reproduce your problem, whatever it is.)

**Comment by koloved** [comment] 2023-12-22 17:28
oh man XD , windows user account, if its not have password on it 
https://www.google.com/search?q=windows+10+user+account+add+password&newwindow=1&client=firefox-b-d&sca_esv=593125510&tbm=isch&sxsrf=AM9HkKnGY9F1kcJFnKNBv5QUcH1fZ6jvcw:1703266105145&source=lnms&sa=X&ved=2ahUKEwjntZ7ZyKODAxUthf0HHUQ_DzYQ_AUoAnoECAEQBA&biw=1920&bih=947&dpr=1#imgrc=drOnTCAdOH_InM

**Comment by Bill-Stewart** [comment] 2023-12-22 17:54
Setup creates a long, random password for the  `SyncthingServiceAccount` account automatically. I still don't understand what it is you are trying to say and what isn't working. If you can clarify the problem and provide sufficient detail for me to reproduce, I'll be happy to take a look, but I'm going to go ahead and close this issue.

**Closed by Bill-Stewart** 2023-12-22 17:54 UTC

**Comment by koloved** [comment] 2023-12-23 12:21
i am not talking about **SyncthingServiceAccount**, there is no any steps , if your user account do not have a password _Syncthing Service_ will not even start , thats it

**Comment by Bill-Stewart** [comment] 2023-12-27 23:04
I just tested this by doing the following:

1. Created a local user account
2. Logged on with that account with no password
3. Installed Syncthing for that user only, and set it to start automatically
4. Logged off from that account
5. Logged on using the account again

When I did that, Syncthing was started as expected.

Whatever your problem is, it seems not to have anything to do with the fact that the account has no password.
