### ISSUE TITLE
Service keeps stopping on Windows 11

### ISSUE THREAD

**Issue by MickMorley** [Bill-Stewart/SyncthingWindowsSetup#18] opened 2024-01-28 23:21 UTC
I have a few installs of SyncthingWindowsSetup but they are all on Windows 10 and only 1 on Windows 11.

The Windows 11 instance is giving me issues.  I see the service (All Users install) starting up upon boot but then it crashes.  I have already reinstalled it just to clear things out.  But the same issue occurred.

I found the below in the event log.  When I manually start up the service again, it stays running. 

![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/19698105/0b6a287f-6ec0-451d-adc4-36198526c3c4)
![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/19698105/68f23e5b-aa66-4fd7-90d1-80cd0d318a51)

**Comment by Bill-Stewart** [comment] 2024-01-28 23:49
Unfortunately I'm not able to reproduce this. I have it installed on several different Windows 11 machines as a service using the `Automatic (Delayed Start)` startup type, and I don't have this problem on any of them. (I have noticed that this startup type means that it can take several minutes after a reboot for the system to actually start the service, but this is normal.)

Exception 0xC0000005 is an access violation. Is it possible to disable your antivirus/antimalware software and reboot to test to see if the problem reoccurs?

**Comment by MickMorley** [comment] 2024-01-29 17:59
Thank you for testing. I wanted to get your input before I tried anything. I use simplewall and disable all windows firewall/services.

I will check to see if disabled/enabling any helps the issues.

I did find there is a recovery feature in Windows Services I was going to try first.  Just have it restart after a failure.

![image](https://github.com/Bill-Stewart/SyncthingWindowsSetup/assets/19698105/253cceae-4775-439e-9892-9e067f6895c6)

**Comment by Bill-Stewart** [comment] 2024-02-01 20:33
> I use simplewall and disable all windows firewall/services.

What happens when you don't use simplewall and instead use the Windows firewall?

**Comment by MickMorley** [comment] 2024-03-08 01:19
I was going to uninstall and try Non Administrative mode.  Unless there is something else that you want me to test?

**Comment by Bill-Stewart** [comment] 2024-03-08 17:06
Sure, feel free to try that, keeping in mind that the configuration data is not shared between the two kinds of installations; see [Finding the Syncthing Configuration Folder](https://github.com/Bill-Stewart/SyncthingWindowsSetup?tab=readme-ov-file#finding-the-syncthing-configuration-folder) in the documentation for more information.

You might also take a look at the `syncthing.log` file from your service instance (should be in the `\ProgramData\Syncthing` directory) as it may provide details about why your service is crashing.

**Comment by Bill-Stewart** [comment] 2024-03-19 18:30
Following up: Does the Syncthing log file give any detail as to why your Syncthing service instance is crashing?

**Comment by Bill-Stewart** [comment] 2024-04-01 18:17
Closing as not reproducible

**Closed by Bill-Stewart** 2024-04-01 18:17 UTC
